### ISSUE TITLE
M2Det

### ISSUE THREAD

**Issue by Sun-Fan** [qijiezhao/M2Det#1]
when will the code be released? According to your table, the M2Det is better than your CFENet, and higher about two points.Thanks. Or if there are paper about M2Det

**Comment by qijiezhao** [comment]
@Sun-Fan  Yeah, thanks for your interest!  It's under review now, we will release it after our latest work (a new method based on M2Det) becomes mature.

**Comment by Sun-Fan** [comment]
thanks.If there are paper about the M2Net

**Comment by qijiezhao** [comment]
The paper is under review now.

**Comment by Sun-Fan** [comment]
Thanks for the reply.
