### ISSUE TITLE
About TUM 

### ISSUE THREAD

**Issue by Ooshita** [qijiezhao/M2Det#10]
Thank you for a wonderful paper.
I want to try implementing M2Det. But there are two things I do not know.
TUM has six outputs, how are they handled and entered in the next TUM?
The second one, please tell me more about backbones. What kind of processing is done on backbone? Thanks.

**Comment by qijiezhao** [comment]
You can leave an email address for me and I send the google drive URL for you.

**Comment by Ooshita** [comment]
oshita@aiqlab.com
Thank you.
