### ISSUE TITLE
Very difficult to download pre-trained weight

### ISSUE THREAD

**Issue by yukkyo** [qijiezhao/M2Det#13]
Hi @qijiezhao !

I tried to download pre-trained weights of M2Det in https://pan.baidu.com/s/1LDkpsQfpaGq_LECQItxRFQ.

But it is little difficult for people who have no account of service of baidu.
(and it is difficult to make own account because my Chinese is not enough 😢 )

Are you planning to be able to download without service of baidu?

**Comment by qijiezhao** [comment]
Certainly! I plan to upload the weight file on Google Drive today.

**Comment by yukkyo** [comment]
Thank you so much for responding soon! 👍 
I'm looking forward to it!

**Comment by qijiezhao** [comment]
https://drive.google.com/file/d/1NM1UDdZnwHwiNDxhcP-nndaWj24m-90L/view?usp=sharing
Also, I have added this link in README.md

**Comment by yukkyo** [comment]
Great !
Thanks for speedy responding !
