### ISSUE TITLE
Speed about M2Det and RFBNet

### ISSUE THREAD

**Issue by tjulyz** [qijiezhao/M2Det#15]
Hi,
Great work!
I have a question about the test speed. As RFBNet reported, they achieve 15ms per image, and SSD get 22ms., while speed of m2det is nearly 30ms. Have you check the speed? Using pytorch 0.4.0+, I cannot get that speed. In your paper, SSD is 43 fps. Is it tested on pytorch 0.4.1 as yours?
Thank you very much!

**Comment by qijiezhao** [comment]
I think we should make fair comparison by running with"CUDA_LAUNCH_BLOCKING=1" before the command. Then the speeds can be fairly compared, because PyTorch has default asynchronous mechanism.

**Comment by tjulyz** [comment]
Sorry, when I add this "CUDA_LAUNCH_BLOCKING=1", the speed becomes really slow... Your speed is tested with this?

**Comment by qijiezhao** [comment]
This command can fairly compare speed of detectors due to that the speed computing program should be synchronized with cpu and gpu. We speed up the detector by saving post-process time through multiprocessing. Then the total time becomes only little longer than the cnn time.

**Comment by tjulyz** [comment]
So, could you please show the details of inference time of CNN and nms time of your network?

**Comment by qijiezhao** [comment]
I plan to list speeds of some one-stage detectors by using CUDA_LAUNCH_BLOCKING=1 next month. (including ssd, dssd, retinanet, refinedet, cornernet and m2det).

**Comment by tjulyz** [comment]
That is really great! Sometimes I find the nms time really has large influence to the final speed. Such as SSD, it is really fast for network inference, but slow for nms. So I think it could be better to compare the speed both with detailed nms time and network time. I am just curious about how long it takes for network inference by M2Det. Refinedet takes 9ms for network and 6ms for nms (I can only got 12ms+ for nms).

**Comment by qijiezhao** [comment]
I know you're curious about the speeds of SOTA detectors, every does. They key point is that the speed is not tested with fair situations. We use multiprocess technique to report the speed in paper(we also reproduce ssd for fair comparison), and RFBNet didn't consider the asynchronous problem. RefineDet ignores I/O time(the I/O cost of CAFFE is less than PyTorch)....
So, It's necessary to report the speeds at a same situation.

**Comment by tjulyz** [comment]
Great! Thanks!
