### ISSUE TITLE
test speed extremely slow with pytorch 0.4.1 and 1.0

### ISSUE THREAD

**Issue by jwnsu** [qijiezhao/M2Det#17]
Tried both pytorch 0.4.1 (cuda9) pytorch 1.0 (cuda10) with m2det. Demo runs fine with downloaded pretrain model. Training (800 config) seems to be fine too, e.g. 4 GPUs are all heavily utilized during training.

However, test speed is around 5s per image (not 5 fps, but 5 seconds per frame! it means many hours to get an evaluaiton score). Look into it closely, it seems GPU has very low utility.

Anyone has seen this issue? Thx.

Env: ubuntu 16.04.6, Nvidia 1080 ti (4 GPUs). Cuda9/cudnn7.2.1 or cuda10/cudnn7.4.1.

**Comment by jwnsu** [comment]
After turns off soft_nms, speed increased about 10x, still get only about 2.5 images/s (for 704x704) input, well below 11.8fps quoted in the paper for 800 size. GPU 1080 Ti is comparable to Titan X.

**Comment by yukkyo** [comment]
I also encountered a similar problem when test.
I improved by using CUDA 9.2.

### Env
- NVIDIA Docker: 1.0.1
- GPU: GTX 1080 ti
- Image Size: 800x800

### Time
- `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04` & `pytorch 0.4.1`
  - It was almost normal(8-10 fps) but occasionally very slow (~10s /per image)
    - It was very slow when I used weight made by other machine
    - But it was strange because it is normal by weight...
- `FROM nvidia/cuda:9.2-devel-ubuntu18.04` & `pytorch 0.4.1`
  - Normal (8-10 fps)
- `FROM nvidia/cuda:9.2-devel-ubuntu18.04` & `pytorch 1.0.1`
  - Little slow (5-6 fps)

**Comment by lg12170226** [comment]
@jwnsu I have the same problem.IT is too slowly
