### ISSUE TITLE
Upsample in TUMs

### ISSUE THREAD

**Issue by YourGc** [qijiezhao/M2Det#18]
Hello,
        Sorry for bothering you，but i want to know more detals about TUMs in your paper . you have written that  it composed of encoder and decoder， how do you achieve “upsample”? Does it make up of convTranspose and Blinear?

**Comment by foralliance** [comment]
@YourGc 
The detailed operation is given in code

**Comment by qijiezhao** [comment]
Yes, you can also use bilinear upsampling:
`return F.interpolate(x, size=(H,W), mode='bilinear',align_corners=True) + y`
