### ISSUE TITLE
cpu version compile

### ISSUE THREAD

**Issue by banayoyo** [qijiezhao/M2Det#19]
is the env without CUDA/CUDNN tested? 
when building the <bash make.sh> with cpu version, raise Error:
<The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME>

**Comment by banayoyo** [comment]
I'v modified parts of the code, and can run now

**Comment by pista10** [comment]
Hi, banayoyo.
I'm trying to run detection with cpu PC(windows - Anaconda), so I approach by comment out nms parts of demo.py (and others).
So I can get im2show images, but they have too many duplicate boxes, probably by comment out 101-104 lines of demo.py.
How do you modified the program?
Thanks.

**Comment by banayoyo** [comment]
> Hi, banayoyo.
> I'm trying to run detection with cpu PC(windows - Anaconda), so I approach by comment out nms parts of demo.py (and others).
> So I can get im2show images, but they have too many duplicate boxes, probably by comment out 101-104 lines of demo.py.
> How do you modified the program?
> Thanks.

there is nearly no modification on demo.py for my repo. U can refer to my github:: m22det/local_m.
maybe u are right, without nms will lead to many duplicated boxes.

**Comment by pista10** [comment]
Thank you, banayoyo.
I understood that the nms problem is caused by not having C compiler and it is slightly difficult to install and setting it on windows PC.
I defined my_cpu_soft_nms() based  by cpu_soft_nms() on cpu_nms.pyx and could get boxes without duplication. 
Thanks.
