### ISSUE TITLE
UnboundLocalError: local variable 'lr' referenced before assignment

### ISSUE THREAD

**Issue by 1451595897** [qijiezhao/M2Det#24]
Hello! When I train the model,it shows that local variable 'lr' referenced before assignment.How can I deal with this problem?
![图片](https://user-images.githubusercontent.com/39090271/54071541-e2e35900-42a8-11e9-9a53-2295f2175dc5.png)

**Comment by Ooshita** [comment]
Edit utils / core.py as follows.from 71 line.

def adjust_learning_rate(optimizer, gamma, epoch, step_index, iteration, epoch_size, cfg):
    global lr
    if epoch <= 5:
    ~
    ~
    ...
