### ISSUE TITLE
/multiprocessing/connection.py", line 379, in _recv     chunk = read(handle, remaining) ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by xinyuegtxy** [qijiezhao/M2Det#28]
how to solve this?
Every time I train the model, when it ran into the end of one epoch, it will happen, how to solve this?

**Comment by qijiezhao** [comment]
It's weird... I didn't met this problem, can you provide more information?

**Comment by WZHsmile** [comment]
I meet the same error ,but I don't know how to solve this problem, so could you give me some suggestion? thx a lot
![error](https://user-images.githubusercontent.com/41030093/59748446-ba0e2f00-92ad-11e9-9a55-661832a5debd.png)

**Comment by WZHsmile** [comment]
> It's weird... I didn't met this problem, can you provide more information?
I meet the same error ,but I don't know how to solve this problem, so could you give me some suggestion? thx a lot
![error](https://user-images.githubusercontent.com/41030093/59748672-30ab2c80-92ae-11e9-8ddd-d7693c0df5e3.png)

**Comment by nththanh** [comment]
Someone know to fix it ?
