### ISSUE TITLE
when will the code be released?

### ISSUE THREAD

**Issue by hust-kevin** [qijiezhao/M2Det#3]

**Comment by JackwithWilshere** [comment]
soon=one hundred years

**Comment by qijiezhao** [comment]
Hi, all.
Thanks for your interest in M2Det.
I am working on a project recently and I decide to refactor M2Det repo to a well-decorated code after that. The release date then relies on the finish date and my collaborator's attitude.

**Comment by epmoon** [comment]
@qijiezhao How is the progress? Is there any schedule?

**Comment by qijiezhao** [comment]
> @qijiezhao How is the progress? Is there any schedule?

I have finished the code and preparing some pre-trained weights.

**Comment by KorovkoAlexander** [comment]
> > @qijiezhao How is the progress? Is there any schedule?
> 
> I have finished the code and preparing some pre-trained weights.

If its possible, could you please share the code at least? Really looking forward for it :)

**Comment by yanxp** [comment]
when will the code be released?
