### ISSUE TITLE
_gt_roidb.pkl

### ISSUE THREAD

**Issue by YuchaoZheng** [qijiezhao/M2Det#33]
I am a newcomer, I want to know how _gt_roidb.pkl came.
Thanks

**Comment by landyfavblue** [comment]
How did you solve it ?

**Comment by YuchaoZheng** [comment]
.pkl is generate  by the program itself

**Comment by PengzhongSun** [comment]
How to generate the .pkl file?
I got into trouble when I run train.py.
![image](https://user-images.githubusercontent.com/43957007/58526767-b2092500-8202-11e9-9810-53ef02251afc.png)
Can you tell me how to solve it?
Thanks!

**Comment by WZHsmile** [comment]
> .pkl is generate by the program itself

I have the same problem. Can you tell me that which file   generate  the .pkl  ? thx

**Comment by yuuho** [comment]
I also have the same problem.
The directory where *_gt_roidb.pkl is stored is not generated automatically.
You need to create the directory yourself.

**Comment by WZHsmile** [comment]
I have solved the problem ,
I manually created the coco_cache file and placed it in the dataset
  COCO ./data/coco under the same path, as follows:

![21320](https://user-images.githubusercontent.com/41030093/60348374-fcdcaf00-99f1-11e9-8650-ec730d0f17e2.png)
