### ISSUE TITLE
Why is the default training setting different from the paper?

### ISSUE THREAD

**Issue by DayChan** [qijiezhao/M2Det#35]
I have a question that if I changed the setting as:
```python3
    lr = [0.002, 0.0002, 0.00002, 0.00002],
    end_lr = 1e-6,
    step_lr = dict(
        COCO = [6, 90, 120, 150],
        )
```
is it same as the setting in the paper?

**Comment by qijiezhao** [comment]
Yes, either is OK. 
We got the results in paper through the above strategy that you mentioned.
We share the strategy in this Repo is always better than the one in paper, you can tune them actually.

**Comment by DayChan** [comment]
> Yes, either is OK.
> We got the results in paper through the above strategy that you mentioned.
> The strategy that share in this Repo is always better than the one in paper, you can tune them actually.

Well,  thanks
