### ISSUE TITLE
About the structure of TUM

### ISSUE THREAD

**Issue by DayChan** [qijiezhao/M2Det#36]
It seems that the TUM structure you used is different from the paper.

I read `class TUM()` in your code, and I draw the structure of TUM:
[My draw of TUM](https://imgur.com/a/NqrXpku)

I don't know whether my draw is right. If it is not, is the structure in the code same as that in the paper? If it's right, why the structure is changed like that?

**Comment by qijiezhao** [comment]
I can't see your image
There indeed exists difference, the arch of original paper is a little better while the arch in this repo is more fancy I think. You can try to modify it in the code.

**Comment by DayChan** [comment]
> I can't see your image
> There indeed exists difference, the arch of original paper is a little better while the arch in this repo is more fancy I think. You can try to modify it in the code.

OK, thanks. You can see it if you connect a VPN outside China.

**Comment by Rainweic** [comment]
Oh I also meet this problem~ But I want to know what’s mean of is_smooth?
