### ISSUE TITLE
resnet v2 maybe better?

### ISSUE THREAD

**Issue by baituhuangyu** [qijiezhao/M2Det#38]
I have a question about resnet here:
[layers/resnet.py](https://github.com/qijiezhao/M2Det/blob/master/layers/resnet.py#L76)

Google says resnet v2 maybe better ?
[resnet-in-tensorflow](https://github.com/tensorflow/models/tree/master/official/resnet#resnet-in-tensorflow)

**Comment by qijiezhao** [comment]
Probably~, You can try to make a comparison.
