### ISSUE TITLE
FFMv1 for resnet-101

### ISSUE THREAD

**Issue by zealota** [qijiezhao/M2Det#4]
In your paper, FFMv1 fuses shallow and deep features.
For resnet-101, if FFMv1 fuses conv4_x and conv5_x, the base feature resolution is 20 x 20.
It is too small for next module.
Could you explain the implementation more detail?

**Comment by qijiezhao** [comment]
Hi, thanks for your interest in our paper.
We **have modified** the stride of Res4 from 2 to 1.
Then, the output of conv1, pool1, Res2, Res3, Res4, Res5 is:
1/2, 1/4, 1/4, 1/8, 1/8 and 1/16. We fuse the output of Res4 and Res5 as the base feature.

**Comment by WangTianYuan** [comment]
Do I need to retrain this modefied ResNet in ImageNet?

**Comment by zealota** [comment]
> Do I need to retrain this modefied ResNet in ImageNet?

In my case, I use the pre-trained model on ImageNet.

**Comment by WangTianYuan** [comment]
So the stride from 2 to 1 doesn't damage the mAP?

**Comment by qijiezhao** [comment]
> So the stride from 2 to 1 doesn't damage the mAP?

Yes, you can directly used the ImageNet-pretrained model. Just like how Pspnet、deeplabv3 use the dilated Resnet.

**Comment by qijiezhao** [comment]
@zealota @WangTianYuan Hi, thanks for your interest in reproducing our results. You can ask me any questions about it here.

**Comment by zealota** [comment]
@WangTianYuan, @qijiezhao 
Sure, the mAP isn't damaged. I could achieve the 0.343 AP(IoU=0.50:0.95)  on coco dataset, for the 320x320 input image.
And I used dilated ResNet.

**Comment by qijiezhao** [comment]
> @WangTianYuan, @qijiezhao
> Sure, the mAP isn't damaged. I could achieve the 0.343 AP(IoU=0.50:0.95) on coco dataset, for the 320x320 input image.
> And I used dilated ResNet.

Congrats! By the way, dilated resnet is not a MUST, this step may slow down the inference speed.

**Comment by xinyuegtxy** [comment]
nice job, 但能把README训练部分写完整点吗？加上各种tricks的训练能开源下吗？thank you.

**Comment by he-y** [comment]
Can you provide the pre-trained model for ResNet101.

**Comment by he-y** [comment]
@zealota 
Hi, Can you provide the pre-trained model for ResNet101?
Thanks!
