### ISSUE TITLE
some wrong i don't know

### ISSUE THREAD

**Issue by rw1995** [qijiezhao/M2Det#40]
please help me.
when i go run with  steps,but something is wrong 
i do **pip install opencv-python,tqdm sh make.sh**,and put the pth into the file "weights",then I run the py **python demo.py -c=configs/m2det512_vgg.py -m=weights/m2det512_vgg.pth --show**, I fund the wrong.

(pytorch0.4.1) csy@csy:~/M2Det$ python demo.py -c=configs/m2det512_vgg.py -m=weights/m2det512_vgg.pth --show
 ----------------------------------------------------------------------
|                       M2Det Demo Program                             |
 ----------------------------------------------------------------------
The Anchor info: 
{'clip': True, 'variance': [0.1, 0.2], 'steps': [8, 16, 32, 64, 128, 256], 'min_dim': 512, 'min_sizes': [30.72, 76.8, 168.96, 261.12, 353.28, 445.44], 'aspect_ratios': [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]], 'feature_maps': [64, 32, 16, 8, 4, 2], 'max_sizes': [76.8, 168.96, 261.12, 353.28, 445.44, 537.6]}
===> Constructing M2Det model
Loading resume network...
===> Finished constructing and loading model
<class 'm2det.M2Det'>
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "demo.py", line 113, in <module>
    out = net(img)
  File "/home/csy/anaconda3/envs/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/csy/M2Det/m2det.py", line 106, in forward
    x = self.base[k](x)
  File "/home/csy/anaconda3/envs/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/csy/anaconda3/envs/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:663

whether i forgot  to modify something in others? I am puzzled or not,please help me

**Comment by door5719** [comment]
I sugest check cuda  and pytorch version.....May be  they are not match ....

**Comment by rw1995** [comment]
> 我sugest检查cuda和pytorch版本.....可能是他们不匹配....
you are right .something is wrong in my torch
