### ISSUE TITLE
A question about SFAM Module

### ISSUE THREAD

**Issue by WangTianYuan** [qijiezhao/M2Det#42]
作者你好，我用你给出的代码复现了论文的结果，非常感谢
但是我注意到config文件中SFAM默认是不使用的，然后我测试了使用SFAM的情况，发现效果没有改进，有些反而变差了，请问是什么原因呢？

**Comment by qijiezhao** [comment]
Hi, SFAM requires more training time to improve the accuracy. I think it's somewhat redundant. If you keep training SFAM for a longer time, then visualize the SFAM feature, you can get a surprise : ). But for the mmAP accuracy, the improvement is somewhat minor.

**Comment by MenGuangwen-CN-0411** [comment]
@WangTianYuan  你好，麻烦问一下，你复现的是论文公布的coco数据集的检测结果么？请问一下训练了多少个epoch？batchsize设置成多大？不胜感激
