### ISSUE TITLE
configs选择m2det320_resnet101.py调试不通

### ISSUE THREAD

**Issue by PigJie2728** [qijiezhao/M2Det#44]
这个网络用vgg训练自己的数据效果不理想，可以选择m2det320_resnet101.py进行训练吗？用resnet一直没有调通。

**Comment by alice7854123** [comment]
你出现的错误是什么 我也没办法

**Comment by PigJie2728** [comment]
已经解决了，^_^。谢谢！

**Comment by lg12170226** [comment]
@PigJie2728 请问一下训练自己的数据的时候有没有遇到#37的问题？就是出现很多误检，而且置信度很高？
