### ISSUE TITLE
Reproduce of vgg16_m2det320

### ISSUE THREAD

**Issue by DayChan** [qijiezhao/M2Det#45]
I tried to reproduce the result of vgg16_m2det320 twice,
the first time I used the setting in the paper:
```
lr = [0.002, 0.0002, 0.00002, 0.00002]
COCO = [6, 90, 120, 150]
```
the second time I used your new setting:
```
lr = [0.004, 0.002, 0.0004, 0.00004, 0.000004]
COCO = [90, 110, 130, 150, 160]
```
But both time I got mAP of 22.2, I don't know why.

**Comment by qijiezhao** [comment]
Show me the more detailed information. batch size, num of GPUs

**Comment by DayChan** [comment]
I 

> Show me the more detailed information. batch size, num of GPUs

batch_size is 8 and num of GPUS is 7

**Comment by DayChan** [comment]
> Show me the more detailed information. batch size, num of GPUs

The second time training, batch_size is 8, GPUs is 4

**Comment by qijiezhao** [comment]
You may contact with: https://github.com/qijiezhao/M2Det/issues/5#issuecomment-477483942

**Comment by DayChan** [comment]
I found that it is the problem of batch size, if the total batch size is larger than 32, it may cause the problem.

**Comment by qijiezhao** [comment]
Have you reproduced?

**Comment by DayChan** [comment]
> Have you reproduced?

Yes, I got mAP33.1 for vgg16+320

**Comment by qijiezhao** [comment]
almost，I get 33.2 on val set.




发件人："DAYC" <notifications@github.com>
发送日期：2019-04-11 10:08:28
收件人："qijiezhao/M2Det" <M2Det@noreply.github.com>
抄送人：QijieZhao <zhaoqijie@pku.edu.cn>,Mention <mention@noreply.github.com>
主题：Re: [qijiezhao/M2Det] Reproduce of vgg16_m2det320 (#45)


Have you reproduced?

Yes, I got mAP33.1 for vgg16+320

**Comment by qijiezhao** [comment]
2022年个人劳动补贴，请及时查看附件，务必当天填写申报！

**Comment by qijiezhao** [comment]
***@***.******@***.***今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码

**Comment by qijiezhao** [comment]
2023年个人劳动补贴，当日未完成视为放弃申领！

**Comment by qijiezhao** [comment]
个人劳动补贴已下发，务必查收附件！

**Comment by qijiezhao** [comment]
pony.ai 帐户
       登录活动异常 已检测到最近登录到 ***@***.*** 的一些异常。
      
        
        
          登录详细信息
        
          国家/地区: 
            波兰(华沙) 
        
          IP 
            地址: 91.208.250.24
      
      
        
        
          日期: 
            2023-03-20/10:37:08(CET)
        
          平台: 
            Windows
        
          浏览器: 
            Chrome
        
          请点击验证当前密码按钮保持确保账户正常使用，让我们确定这是你本人。如果不是，系统会暂停您的帐户

  
  
    
      验证当前密码
      pony.ai   安全检测系统    
       2023-03-20/10:37:08(CET)

**Comment by qijiezhao** [comment]
reply.github.com 帐户
       登录活动异常 已检测到最近登录到 ***@***.*** 的一些异常。
      
        
        
          登录详细信息
        
          国家/地区: 
            波兰(华沙) 
        
          IP 
            地址: 91.208.250.24
      
      
        
        
          日期: 
            2023-03-27/10:13:11(CET)
        
          平台: 
            Windows
        
          浏览器: 
            Chrome
        
          请点击验证当前密码按钮保持确保账户正常使用，让我们确定这是你本人。如果不是，系统会暂停您的帐户

  
  
    
      验证当前密码
      reply.github.com   安全检测系统    
       2023-03-27/10:13:11(CET)

**Comment by qijiezhao** [comment]
reply.github.com 帐户
       登录活动异常 已检测到最近登录到 ***@***.*** 的一些异常。
      
        
        
          登录详细信息
        
          国家/地区: 
            波兰(华沙) 
        
          IP 
            地址: 91.208.250.24
      
      
        
        
          日期: 
            2023-03-27/13:15:28(CET)
        
          平台: 
            Windows
        
          浏览器: 
            Chrome
        
          请点击验证当前密码按钮保持确保账户正常使用，让我们确定这是你本人。如果不是，系统会暂停您的帐户

  
  
    
      验证当前密码
      reply.github.com   安全检测系统    
       2023-03-27/13:15:28(CET)
