### ISSUE TITLE
about detect speed

### ISSUE THREAD

**Issue by moyans** [qijiezhao/M2Det#57]
@qijiezhao 
training with customed dataset, test 320(15fps)/512(12fps) is normal? close softnms
titan x / cuda8 

320*320
----------------------------------------------------------------------
|                       M2Det Evaluation Program                     |
----------------------------------------------------------------------
The Anchor info: 
{'feature_maps': [40, 20, 10, 5, 3, 1], 'min_dim': 320, 'steps': [8, 16, 32, 64, 107, 320], 'min_sizes': [25.6, 48.0, 105.6, 163.2, 220.8, 278.4], 'max_sizes': [48.0, 105.6, 163.2, 220.8, 278.4, 336.0], 'aspect_ratios': [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]], 'variance': [0.1, 0.2], 'clip': True}
===> Constructing M2Det model
Loading resume network...
===> Finished constructing and loading model
loading annotations into memory...
Done (t=0.29s)
creating index...
index created!
SKUDetHJ190316CheckData2014 gt roidb loaded from ./data/coco_cache/SKUDetHJ190316CheckData2014_gt_roidb.pkl
=> Total 779 images to test.
Begin to evaluate
100%|█████| 779/779 [01:24<00:00,  7.69it/s]
Detect time per image: 0.063s
Nms time per image: 0.001s
Total time per image: 0.064s
FPS: 15.710 fps

512*512
----------------------------------------------------------------------
|                       M2Det Evaluation Program                     |
----------------------------------------------------------------------
The Anchor info: 
{'feature_maps': [64, 32, 16, 8, 4, 2], 'min_dim': 512, 'steps': [8, 16, 32, 64, 128, 256], 'min_sizes': [30.72, 76.8, 168.96, 261.12, 353.28, 445.44], 'max_sizes': [76.8, 168.96, 261.12, 353.28, 445.44, 537.6], 'aspect_ratios': [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]], 'variance': [0.1, 0.2], 'clip': True}
===> Constructing M2Det model
Loading resume network...
===> Finished constructing and loading model
loading annotations into memory...
Done (t=0.29s)
creating index...
index created!
SKUDetHJ190316CheckData2014 gt roidb loaded from ./data/coco_cache/SKUDetHJ190316CheckData2014_gt_roidb.pkl
=> Total 779 images to test.
Begin to evaluate
100%|█████████| 779/779 [01:38<00:00,  6.44it/s]
Detect time per image: 0.079s
Nms time per image: 0.001s
Total time per image: 0.080s
FPS: 12.483 fps

**Comment by cherishfive** [comment]
Hello, I tested on the pascal voc dataset. The speed is only 0.3fps. What happened?

**Comment by moyans** [comment]
> Hello, I tested on the pascal voc dataset. The speed is only 0.3fps. What happened?

sorry, I have no idea
