### ISSUE TITLE
about tum conv out 128

### ISSUE THREAD

**Issue by ryzejiang** [qijiezhao/M2Det#71]
您好,不好意思打扰您了.

我在论文中看见了TUM模块中最下面一层有多个输出通道为128的卷积核,论文中的图片将其称之为Brief indication.

但是我在您的TUM代码中没有发现代码有新建输出通道为128的BasicConv,几乎都是输出的256通道的,非常不解,是不是我在理解上有问题,想请教您一下.

**Comment by lg12170226** [comment]
@ryzejiang 请问一下 我也发现TUM模块中输出都为256，没有发现128，求解

**Comment by ryzejiang** [comment]
@lg12170226 我看了代码，输出就是256。事实就是论文和代码不一致。。。从第二个TUM开始，TUM 的输入就都是384了（384=128+256），还没有试过128的结果会不会比代码中的256要好。
