### ISSUE TITLE
Reproduction of articles, the effect is very poor

### ISSUE THREAD

**Issue by csu-xiewei** [qijiezhao/M2Det#8]
Reproduction of articles, the effect is not ideal

**Comment by qijiezhao** [comment]
I **AM** working on preparing the code, don't worry. 
If you want to find the reason(why the score is low), just list all the important information here and I will try to help you.

**Comment by convolutionROC** [comment]
@qijiezhao When will the code be available? The reported result seems to be great and I also want to realize it.
