### ISSUE TITLE
JIT trace model problem

### ISSUE THREAD

**Issue by jinfagang** [qijiezhao/M2Det#82]
Hi, I'd like to trace your model into C++ inference. it seems your model has modules share parameters rather than reuse, it can not be trace in both libtorch or onnx.

However, hardly to locate which modules sharing parameters. I wanna ask, which modules using has been shared? Is that possible changed into reuse module rather than sharing parameters?

I got some error when tracing the model:

```
    traced_script_module = torch.jit.trace(net, example)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 686, in trace
    traced = _module_class(func, **executor_options)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
    original_init(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
    original_init(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1482, in __init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
    original_init(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1482, in __init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
    original_init(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1482, in __init__
    self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
    original_init(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1469, in __init__
    check_unique(param)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1461, in check_unique
    raise ValueError("TracedModules don't support parameter sharing between modules")
ValueError: TracedModules don't support parameter sharing between modules

```

**Comment by defenceVT** [comment]
> I got some error when tracing the model:

Have you solved the problem?

**Comment by defenceVT** [comment]
> Hi, I'd like to trace your model into C++ inference. it seems your model has modules share parameters rather than reuse, it can not be trace in both libtorch or onnx.
> However, hardly to locate which modules sharing parameters. I wanna ask, which modules using has been shared? Is that possible changed into reuse module rather than sharing parameters?
> I got some error when tracing the model:
>     traced_script_module = torch.jit.trace(net, example)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 686, in trace
>     traced = _module_class(func, **executor_options)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
>     original_init(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
>     original_init(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1482, in __init__
>     self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
>     original_init(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1482, in __init__
>     self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
>     original_init(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1482, in __init__
>     self._modules[name] = TracedModule(submodule, id_set, optimize=optimize)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1046, in init_then_register
>     original_init(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1469, in __init__
>     check_unique(param)
>   File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1461, in check_unique
>     raise ValueError("TracedModules don't support parameter sharing between modules")
> ValueError: TracedModules don't support parameter sharing between modules

Have you solved the problem? @jinfagang

**Comment by halcyon370** [comment]
It seems self.leach has some weights being shared:
`self.leach = nn.ModuleList([BasicConv(
                    deep_out+shallow_out,
                    self.planes//2,
                    kernel_size=(1,1),stride=(1,1))]*self.num_levels)`
Maybe it should be this:
`self.leach = nn.ModuleList([BasicConv(
            deep_out + shallow_out,
            self.planes // 2,
            kernel_size=(1, 1), stride=(1, 1)) for _ in range(self.num_levels)])`
I am not sure whether it is a bug.
