### ISSUE TITLE
about 2015 test-dev？

### ISSUE THREAD

**Issue by qq276399331** [qijiezhao/M2Det#9]
可以公开下你们的数据集的选择么是在2017coco数据集还是以前的版本的coco呢，你们的评估服务器是怎么提交的呢？2015 test-dev么

**Comment by qijiezhao** [comment]
We submit the result of test set(test-dev) on: https://competitions.codalab.org/competitions/5181#results

You can still find us ranked 14th on the leaderboard.
`
14 | nemonameless | 6 | 09/02/18 | M2Det | 0.442 (14) | 0.646 (13) | 0.493 (11) | 0.292 (9) | 0.479 (9) | 0.551 (17) | 0.344 (14) | 0.571 (13) | 0.622 (11) | 0.431 (13) | 0.658 (13) | 0.769 (11)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
`

**Comment by qijiezhao** [comment]
As I known, test-dev 2015 is the same as test-dev 2018.

**Comment by qq276399331** [comment]
很感谢您的回信，我发现好像总是无法提交上去
